# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:title/

baseurl: /
encoding: utf-8

markdown: kramdown
# markdown: redcarpet
# redcarpet:
#  extensions: ["no_intra_emphasis", "autolink", "tables"]
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "TODO.md", "tools", "Dockerfile", "plan"]
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 50

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#

title : 泰晓科技
tagline: 聚焦 Linux - 追本溯源，见微知著！
start: 2010

production_url: http://tinylab.org

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: []

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.3.0

  BASE_PATH : false
  
  ASSET_PATH : false
  IMAGE_PATH : false
  
  theme_name: tinylab.org

  archive_path: /archive/
  authors_path: /authors/
  categories_path : /categories/
  tags_path : /tags/
  albums_path: /albums/
  groups_path: /groups/
  atom_path : /atom.xml
  rss_path : /rss.xml

  posts:
    title_length: 50
    related_limit: 5
  sidebar:
    items_limit: 5
  author_box:
    max_perline: 6
  article:
    categories_limit: 3

  code_prettify:
    theme: doxy

  comments :
    provider : changyan
    changyan:
      appid: cysUrhPh4
      conf: prod_fbd8fc8ac3f8dd0f7d1997acd736ef58
    duoshuo :
      short_name : tinylab
    disqus :
      short_name : tinylab

  analytics :
    providers :
      - baidu
      - cnzz
    baidu :
      tracking_id : '15260089f8e103dc1cca30bcc1957b7c'
    cnzz :
      tracking_id : '5542089'

  sharing :
    provider : false
